// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWgt47A-B3Hka1WgPp_0r9tVSxEJ3Svls',
    appId: '1:508691236350:android:2115e453876fda854f6caf',
    messagingSenderId: '508691236350',
    projectId: 'my-chatoo-chat',
    storageBucket: 'my-chatoo-chat.firebasestorage.app',
    databaseURL: 'https://my-chatoo-chat-default-rtdb.firebaseio.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ3mF-vT7JP0IGrhqkjbh5AzeUtcrB5wc',
    appId: '1:508691236350:ios:66a3e8de84b891f54f6caf',
    messagingSenderId: '508691236350',
    projectId: 'my-chatoo-chat',
    storageBucket: 'my-chatoo-chat.firebasestorage.app',
    databaseURL: 'https://my-chatoo-chat-default-rtdb.firebaseio.com',
    androidClientId:
        '508691236350-egvn0e5eqggfnd70s34dc4lr21p2lnpk.apps.googleusercontent.com',
    iosClientId:
        '508691236350-etce5tmd9s5r844s2idebd6njhnctt0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChatooChat',
  );
}
